### ISSUE TITLE
How to compile the example?

### ISSUE THREAD

**Issue by tgulacsi** [influx6/govfx#1]
! go version
go version go1.6 linux/amd64

$ go get -u github.com/influx6/govfx/...
package github.com/influx6/govfx/tests/elementals
        imports github.com/influx6/faux/vfx: cannot find package "github.com/influx6/faux/vfx" in any of:
        /usr/local/go/src/github.com/influx6/faux/vfx (from $GOROOT)
        /home/tgulacsi/src/github.com/influx6/faux/vfx (from $GOPATH)
:tgulacsi@tgulacsi-Aspire-V3-371: ~
! rm -rf /home/tgulacsi/src/github.com/gopherjs
:tgulacsi@tgulacsi-Aspire-V3-371: ~
! go get -u github.com/gopherjs/gopherjs/...  
:tgulacsi@tgulacsi-Aspire-V3-371: ~/src/github.com/influx6/govfx/examples/shadowDOM
! env GO15VENDOREXPERIMENT=0 gopherjs build app.go
panic: runtime error: invalid memory address or nil pointer dereference [recovered]

The same with GO15VENDOREXPERIMENT=0, too

**Comment by influx6** [comment]
Thanks, will look into and get back to you, seems I made the error by using go1.5, will get 1.6 running asap

**Comment by influx6** [comment]
I have yet to resolve this issue and its late evening here, so I will report asap here tomorrow, sorry for the wait 🙂

**Comment by tgulacsi** [comment]
No problemo, thanks!

Ewetumo Alexander notifications@github.com ezt írta (időpont: 2016. febr.
23., K, 21:50):

**Comment by influx6** [comment]
This case is odd to be honest, am yet to reproduce the same situation, although am on windows, even with Go1.6 and latest gopherjs repulled, mine compiles without any errors. Although I add to remove the old gopherjs binary from the Go/bin directory.

Would you like to do a screenshare over screenhero?

Aside: I have fixed the package import errors.

**Comment by tgulacsi** [comment]
The problem lies in gopherjs https://github.com/gopherjs/gopherjs/pull/409
With that patch, the example compiles.

So sorry for the red herring, and thanks for your efforts!

**Comment by influx6** [comment]
No problem, happy it's all resolved.

**Comment by influx6** [comment]
@tgulacsi I hope you tests were successfull, I hope to add more animators into the lists to expand the effects soon. Do tell me where you need help or ideas on improvement
