### ISSUE TITLE
Suggestion, make it easier to look at the results (the example).

### ISSUE THREAD

**Issue by dmitshur** [influx6/govfx#3]
Right now, there's code in the README that provides an example:

https://github.com/influx6/govfx#example

That's great! But it can be even better if you can create a static page somewhere with the result, so any visitor can quickly click on a link and see what it looks like.

This is especially helpful for those who don't know what Velocity.js is.

It'd also be good to justify the large codebase size; otherwise it's hard to know why there's so much code and what it does.

This is just a suggestion, feel free to close and act on it as you think is best.

**Comment by influx6** [comment]
Thanks bro, will gets those sorted, just trying to make time to expand the animators lists, css3 transforms giving some headaches. Thanks will definitely get these sorted soon. Appreciate you taking the time.

**Comment by influx6** [comment]
Some a few changes as per your ideas, will try to get the sample static pages up today

**Comment by influx6** [comment]
The sample links to view each example has been added. If you have more ideas, they are warmly welcome. Cheers.

**Comment by dmitshur** [comment]
Awesome, thanks for doing that, it's very helpful for onlookers to be able to check out the project that much more quickly!

**Comment by influx6** [comment]
Resolved in #159686e1e7fe12066497baa952bc060c8821bb1e
