### ISSUE TITLE
Fenced code blocks in README have unneeded indentation.

### ISSUE THREAD

**Issue by dmitshur** [influx6/govfx#4]
The fenced code blocks currently look like this:

``````
```bash

  go get -u github.com/influx6/govfx/...

```
``````

Which renders like this:

``` bash

  go get -u github.com/influx6/govfx/...

```

Note there are 2 unneeded spaces in front of the `go get -u`.

You don't need to indent what's inside fenced code blocks. The blank lines on the inside aren't neccessary either. You can instead write this:

``````
```bash
go get -u github.com/influx6/govfx/...
```
``````

Which renders like this:

``` bash
go get -u github.com/influx6/govfx/...
```

You can read more about fenced code blocks at https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by dmitshur** [comment]
A plug, you could consider using [`markdownfmt`](https://github.com/shurcooL/markdownfmt) to format your Markdown. You can try it in your browser [here](https://dmitri.shuralyov.com/projects/live-markdown/live-markdown.html) first. :)

**Comment by influx6** [comment]
Awesome, thanks bro, will get these sorted tomorrow morning
